# Site settings
title: William Martins
email: wwwhmartins@gmail.com
description: >
    Random thoughts about code
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wmartins.github.io" # the base hostname & protocol for your site
twitter_username: wwwhmartins
github_username:  wmartins

# Build settings
markdown: kramdown
