baseURL = "http://wmartins.github.io"
languageCode = "en-us"
title = "wwwhmartins"
theme = "pixyll"

[params]
    google_analytics_id = "UA-68493929-1"

[permalinks]
    post = "/:year/:month/:title/"
